### ISSUE TITLE
Error when trying to edit an Asset

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph_assets#485]
When trying to click on Device link or Actions/Edit button I get the following error
(Ralph 2.0.1 , Ralph Assets 2.2.0)

![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/4737255/77c80744-59f3-11e4-98b6-b16980de54a8.JPG)

```
[22.10.2014 15:42:33,738] ERROR   [MainProcess 22781] base - Internal Server Error: /assets/dc/edit/device/1/
Traceback (most recent call last):
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 134, in get_response
    response = response.render()
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 478, in render
    output = self.nodelist.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 186, in render
    nodelist.append(node.render(context))
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 186, in render
    nodelist.append(node.render(context))
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 478, in render
    output = self.nodelist.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 282, in render
    return nodelist.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 1202, in render
    return self.nodelist.render(new_context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/ralph/local/lib/python2.7/site-packages/django/template/debug.py", line 87, in render
    output = force_unicode(output)
  File "/home/ralph/local/lib/python2.7/site-packages/django/utils/encoding.py", line 71, in force_unicode
    s = unicode(s)
  File "/home/ralph/local/lib/python2.7/site-packages/django/forms/forms.py", line 411, in __unicode__
    return self.as_widget()
  File "/home/ralph/local/lib/python2.7/site-packages/django/forms/forms.py", line 458, in as_widget
    return widget.render(name, self.value(), attrs=attrs)
  File "/home/ralph/local/lib/python2.7/site-packages/ajax_select/fields.py", line 188, in render
    url = lookup.get_item_url(obj)
  File "/home/ralph/local/lib/python2.7/site-packages/ralph_assets/models.py", line 250, in get_item_url
    return obj.url
  File "/home/ralph/local/lib/python2.7/site-packages/ralph_assets/models_support.py", line 108, in url
    'mode': ASSET_TYPE2MODE[self.asset_type],
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 500, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 420, in _reverse_with_prefix
    "arguments '%s' not found." % (lookup_view_s, args, kwargs))
NoReverseMatch: Reverse for 'edit_support' with arguments '()' and keyword arguments '{u'support_id': 1L, u'mode': u'other'}' not found.
```

**Comment by vi4m** [comment]
Open?

**Comment by ar4s** [comment]
@vi4m resolved
