### ISSUE TITLE
Error matching discovered device with an Asset

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph_assets#486]
This errors refers to the other issue submitted by me by mistake in the main Ralph module [#1160](http://github.com/allegro/ralph/issues/1160)

![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/4737861/9dee2ec6-59f8-11e4-8442-07e0df8fb73d.JPG)
After selecting 'Ralph device id' in Additional Info section and clicking Save button I get the following error
```
[22.10.2014 16:24:52,481] ERROR   [MainProcess 22781] base - Internal Server Error: /assets/dc/edit/device/12/
Traceback (most recent call last):
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/ralph_assets/views/base.py", line 70, in dispatch
    return super(AssetsBase, self).dispatch(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/account/models.py", line 273, in inner_decorator
    return func(self, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/ralph_assets/views/base.py", line 52, in dispatch
    return super(ACLGateway, self).dispatch(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/ralph_assets/views/device.py", line 262, in post
    self.additional_info.is_valid(),
  File "/home/ralph/local/lib/python2.7/site-packages/django/forms/forms.py", line 124, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/home/ralph/local/lib/python2.7/site-packages/django/forms/forms.py", line 115, in _get_errors
    self.full_clean()
  File "/home/ralph/local/lib/python2.7/site-packages/django/forms/forms.py", line 271, in full_clean
    self._clean_form()
  File "/home/ralph/local/lib/python2.7/site-packages/django/forms/forms.py", line 299, in _clean_form
    self.cleaned_data = self.clean()
  File "/home/ralph/local/lib/python2.7/site-packages/ralph_assets/forms.py", line 551, in clean
    mark_safe(msg.format(escape(device_info.asset.id)))
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 255, in __get__
    rel_obj = self.get_query_set(instance=instance).get(**params)
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/query.py", line 366, in get
    % self.model._meta.object_name)
DoesNotExist: Asset matching query does not exist.
```

**Comment by vi4m** [comment]
Resolved?

**Comment by damian1976** [comment]
Let's close it for now - probably resolved
