### ISSUE TITLE
Cannot add asset with multiple devices (barcodes)

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph_assets#549]
When trying to add an asset and typing multiple SNs and barcodes in the textarea (single 'Position' inserted) I get the following error:

[22.12.2014 14:09:47,181] ERROR   [MainProcess 22403] base - Internal Server Error: /assets/dc/add/device/
Traceback (most recent call last):
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ralph/ralph_assets/src/ralph_assets/views/base.py", line 72, in dispatch
    return super(AssetsBase, self).dispatch(request, *args, **kwargs)
  File "/home/ralph/ralph_develop/src/ralph/account/models.py", line 297, in inner_decorator
    return func(self, *args, **kwargs)
  File "/home/ralph/ralph_assets/src/ralph_assets/views/base.py", line 56, in dispatch
    return super(ACLGateway, self).dispatch(request, *args, **kwargs)
  File "/home/ralph/ralph_develop/src/ralph/ui/views/common.py", line 248, in dispatch
    return super(MenuMixin, self).dispatch(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ralph/ralph_assets/src/ralph_assets/views/device.py", line 115, in post
    self.mode
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/transaction.py", line 224, in inner
    return func(*args, **kwargs)
  File "/home/ralph/ralph_assets/src/ralph_assets/views/utils.py", line 59, in _create_assets
    asset.save(user=creator_profile.user, force_unlink=force_unlink)
  File "/home/ralph/ralph_assets/src/ralph_assets/models_assets.py", line 730, in save
    self.handle_device_linkage(force_unlink)
  File "/home/ralph/ralph_assets/src/ralph_assets/models_assets.py", line 724, in handle_device_linkage
    self.device_info.save()
  File "/home/ralph/local/lib/python2.7/site-packages/lck/django/common/models.py", line 201, in save
    super(TimeTrackable, self).save(*args, **kwargs)
  File "/home/ralph/ralph_develop/src/ralph/discovery/models_util.py", line 37, in save
    return super(SavingUser, self).save(user=user, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/lck/django/common/monkeys.py", line 44, in <lambda>
    using)
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/base.py", line 529, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/query.py", line 560, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 988, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/home/ralph/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/home/ralph/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry '131' for key 'ralph_device_id'")

**Comment by vi4m** [comment]
@ar4s well we should handle it better, don't you think?

**Comment by vi4m** [comment]
What about it?

**Comment by ar4s** [comment]
Asset is linked with device by relation one-to-one. Please add one asset with SN and barcode per device which does not change the fact - we must handle this case and display suitable message.

**Comment by vi4m** [comment]
I don't understand. Some duplicated barcodes/sn in the asset add list ? Or previously added into the core devices with sn/barcodes ?

**Comment by damian1976** [comment]
I cannot reproduce this error now (after 2 months since this issue was raised). Let's close it. In case it appears again I will reopen it.
